build:
  environment:
    php:
      version: "7.1.0"
  dependencies:
    before:
      - composer self-update
      - composer install --prefer-source --no-interaction --dev
  checks:
    php:
      code_rating: true
      duplication: true
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=clover'
        coverage:
          file: 'clover'
          format: 'clover'
